// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.21.12
// source: v1/manager/manager.proto

package manager

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationManagerCreate = "/v1.manager.Manager/Create"

type ManagerHTTPServer interface {
	// Create Manager detection
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterManagerHTTPServer(s *http.Server, srv ManagerHTTPServer) {
	r := s.Route("/")
	r.POST("/api/manager/create", _Manager_Create0_HTTP_Handler(srv))
}

func _Manager_Create0_HTTP_Handler(srv ManagerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationManagerCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateResponse)
		return ctx.Result(200, reply)
	}
}

type ManagerHTTPClient interface {
	Create(ctx context.Context, req *CreateRequest, opts ...http.CallOption) (rsp *CreateResponse, err error)
}

type ManagerHTTPClientImpl struct {
	cc *http.Client
}

func NewManagerHTTPClient(client *http.Client) ManagerHTTPClient {
	return &ManagerHTTPClientImpl{client}
}

func (c *ManagerHTTPClientImpl) Create(ctx context.Context, in *CreateRequest, opts ...http.CallOption) (*CreateResponse, error) {
	var out CreateResponse
	pattern := "/api/manager/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationManagerCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
