// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"mt/config"
	"mt/internal/api"
	"mt/internal/biz"
	"mt/internal/data"
	"mt/internal/server"
	"mt/internal/service"
	"mt/pkg/logger"
	"mt/pkg/repositories"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(configServer *config.Server, configData *config.Data, app *config.App, websocket *config.Websocket, loggerLogger *logger.Logger) (*kratos.App, func(), error) {
	dataRepo := repositories.NewDataRepo(loggerLogger, configData)
	dataData, cleanup, err := data.NewData(configData, loggerLogger, dataRepo)
	if err != nil {
		return nil, nil, err
	}
	heartbeatRepo := data.NewHeartbeatRepo(dataData, loggerLogger)
	heartbeatUsecase := biz.NewHeartbeatUsecase(heartbeatRepo, loggerLogger)
	heartbeatService := service.NewHeartbeatService(heartbeatUsecase)
	accountRepo := data.NewAccountRepo(dataData, loggerLogger)
	accountUsecase := biz.NewAccountUsecase(accountRepo, loggerLogger)
	accountService := service.NewAccountService(accountUsecase)
	grpcServer := server.NewGRPCServer(configServer, heartbeatService, accountService, loggerLogger)
	handler := api.NewHandler(app, websocket, loggerLogger, dataRepo)
	httpServer := server.NewHTTPServer(configServer, heartbeatService, accountService, handler, loggerLogger)
	kratosApp := newApp(loggerLogger, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
